name: posterapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  google_fonts: ^6.2.1
  assets: ^0.0.1
  fluttertoast: ^8.2.6
  firebase_database: ^11.0.1
  image_picker: ^1.1.2
  firebase_storage: ^12.0.1
  share_plus: ^9.0.0
  provider: ^6.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/